# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cost.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cost.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z)github.com/JBurton26/msoa-go/protos/cost/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncost.proto\"H\n\x06\x42\x61sket\x12\x1b\n\x05Items\x18\x01 \x03(\x0b\x32\x0c.Basket.Item\x1a!\n\x04Item\x12\n\n\x02ID\x18\x01 \x01(\t\x12\r\n\x05\x43ount\x18\x02 \x01(\x03\"\x19\n\x0b\x43ostRequest\x12\n\n\x02ID\x18\x01 \x01(\t\"*\n\rUpdateRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12\r\n\x05Price\x18\x02 \x01(\x01\"\x1d\n\x0c\x43ostResponse\x12\r\n\x05Price\x18\x01 \x01(\x01\"!\n\x0eUpdateResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x32\xbc\x01\n\x04\x43ost\x12*\n\x0bGetUnitCost\x12\x0c.CostRequest\x1a\r.CostResponse\x12\x31\n\x0eUpdateUnitCost\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12.\n\x0b\x41\x64\x64UnitCost\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12%\n\x0bTotalBasket\x12\x07.Basket\x1a\r.CostResponseB+Z)github.com/JBurton26/msoa-go/protos/cost/b\x06proto3'
)




_BASKET_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Basket.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Basket.Item.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Count', full_name='Basket.Item.Count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=86,
)

_BASKET = _descriptor.Descriptor(
  name='Basket',
  full_name='Basket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Items', full_name='Basket.Items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BASKET_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=86,
)


_COSTREQUEST = _descriptor.Descriptor(
  name='CostRequest',
  full_name='CostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='CostRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=113,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='UpdateRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Price', full_name='UpdateRequest.Price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=157,
)


_COSTRESPONSE = _descriptor.Descriptor(
  name='CostResponse',
  full_name='CostResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Price', full_name='CostResponse.Price', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=188,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Success', full_name='UpdateResponse.Success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=223,
)

_BASKET_ITEM.containing_type = _BASKET
_BASKET.fields_by_name['Items'].message_type = _BASKET_ITEM
DESCRIPTOR.message_types_by_name['Basket'] = _BASKET
DESCRIPTOR.message_types_by_name['CostRequest'] = _COSTREQUEST
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['CostResponse'] = _COSTRESPONSE
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Basket = _reflection.GeneratedProtocolMessageType('Basket', (_message.Message,), {

  'Item' : _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
    'DESCRIPTOR' : _BASKET_ITEM,
    '__module__' : 'cost_pb2'
    # @@protoc_insertion_point(class_scope:Basket.Item)
    })
  ,
  'DESCRIPTOR' : _BASKET,
  '__module__' : 'cost_pb2'
  # @@protoc_insertion_point(class_scope:Basket)
  })
_sym_db.RegisterMessage(Basket)
_sym_db.RegisterMessage(Basket.Item)

CostRequest = _reflection.GeneratedProtocolMessageType('CostRequest', (_message.Message,), {
  'DESCRIPTOR' : _COSTREQUEST,
  '__module__' : 'cost_pb2'
  # @@protoc_insertion_point(class_scope:CostRequest)
  })
_sym_db.RegisterMessage(CostRequest)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'cost_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

CostResponse = _reflection.GeneratedProtocolMessageType('CostResponse', (_message.Message,), {
  'DESCRIPTOR' : _COSTRESPONSE,
  '__module__' : 'cost_pb2'
  # @@protoc_insertion_point(class_scope:CostResponse)
  })
_sym_db.RegisterMessage(CostResponse)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'cost_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)


DESCRIPTOR._options = None

_COST = _descriptor.ServiceDescriptor(
  name='Cost',
  full_name='Cost',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUnitCost',
    full_name='Cost.GetUnitCost',
    index=0,
    containing_service=None,
    input_type=_COSTREQUEST,
    output_type=_COSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUnitCost',
    full_name='Cost.UpdateUnitCost',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddUnitCost',
    full_name='Cost.AddUnitCost',
    index=2,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TotalBasket',
    full_name='Cost.TotalBasket',
    index=3,
    containing_service=None,
    input_type=_BASKET,
    output_type=_COSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COST)

DESCRIPTOR.services_by_name['Cost'] = _COST

# @@protoc_insertion_point(module_scope)
