# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inventory.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z.github.com/JBurton26/msoa-go/protos/inventory/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finventory.proto\",\n\x0cLevelRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x10\n\x08Location\x18\x02 \x01(\t\" \n\x0cShortRequest\x12\x10\n\x08Location\x18\x01 \x01(\t\"Y\n\x0c\x41mendRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x10\n\x08Location\x18\x02 \x01(\t\x12\x0e\n\x06\x41mount\x18\x03 \x01(\x03\x12\x0c\n\x04Name\x18\x04 \x01(\t\x12\r\n\x05Price\x18\x05 \x01(\x01\"!\n\rAmendResponse\x12\x10\n\x08Response\x18\x01 \x01(\t\"K\n\tStockItem\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x10\n\x08Location\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x12\n\nStockCount\x18\x04 \x01(\x03\"&\n\tShortList\x12\x19\n\x05SList\x18\x01 \x03(\x0b\x32\n.StockItem2\xb0\x01\n\tInventory\x12%\n\x08GetStock\x12\r.LevelRequest\x1a\n.StockItem\x12,\n\x0b\x43hangeStock\x12\r.AmendRequest\x1a\x0e.AmendResponse\x12\'\n\nCheckShort\x12\r.ShortRequest\x1a\n.ShortList\x12%\n\x08GetStore\x12\r.ShortRequest\x1a\n.ShortListB0Z.github.com/JBurton26/msoa-go/protos/inventory/b\x06proto3'
)




_LEVELREQUEST = _descriptor.Descriptor(
  name='LevelRequest',
  full_name='LevelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='LevelRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='LevelRequest.Location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=63,
)


_SHORTREQUEST = _descriptor.Descriptor(
  name='ShortRequest',
  full_name='ShortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Location', full_name='ShortRequest.Location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=97,
)


_AMENDREQUEST = _descriptor.Descriptor(
  name='AmendRequest',
  full_name='AmendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='AmendRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='AmendRequest.Location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Amount', full_name='AmendRequest.Amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='AmendRequest.Name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Price', full_name='AmendRequest.Price', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=188,
)


_AMENDRESPONSE = _descriptor.Descriptor(
  name='AmendResponse',
  full_name='AmendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Response', full_name='AmendResponse.Response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=223,
)


_STOCKITEM = _descriptor.Descriptor(
  name='StockItem',
  full_name='StockItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='StockItem.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='StockItem.Location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='StockItem.Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StockCount', full_name='StockItem.StockCount', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=300,
)


_SHORTLIST = _descriptor.Descriptor(
  name='ShortList',
  full_name='ShortList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SList', full_name='ShortList.SList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=340,
)

_SHORTLIST.fields_by_name['SList'].message_type = _STOCKITEM
DESCRIPTOR.message_types_by_name['LevelRequest'] = _LEVELREQUEST
DESCRIPTOR.message_types_by_name['ShortRequest'] = _SHORTREQUEST
DESCRIPTOR.message_types_by_name['AmendRequest'] = _AMENDREQUEST
DESCRIPTOR.message_types_by_name['AmendResponse'] = _AMENDRESPONSE
DESCRIPTOR.message_types_by_name['StockItem'] = _STOCKITEM
DESCRIPTOR.message_types_by_name['ShortList'] = _SHORTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LevelRequest = _reflection.GeneratedProtocolMessageType('LevelRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEVELREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:LevelRequest)
  })
_sym_db.RegisterMessage(LevelRequest)

ShortRequest = _reflection.GeneratedProtocolMessageType('ShortRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHORTREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:ShortRequest)
  })
_sym_db.RegisterMessage(ShortRequest)

AmendRequest = _reflection.GeneratedProtocolMessageType('AmendRequest', (_message.Message,), {
  'DESCRIPTOR' : _AMENDREQUEST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:AmendRequest)
  })
_sym_db.RegisterMessage(AmendRequest)

AmendResponse = _reflection.GeneratedProtocolMessageType('AmendResponse', (_message.Message,), {
  'DESCRIPTOR' : _AMENDRESPONSE,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:AmendResponse)
  })
_sym_db.RegisterMessage(AmendResponse)

StockItem = _reflection.GeneratedProtocolMessageType('StockItem', (_message.Message,), {
  'DESCRIPTOR' : _STOCKITEM,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:StockItem)
  })
_sym_db.RegisterMessage(StockItem)

ShortList = _reflection.GeneratedProtocolMessageType('ShortList', (_message.Message,), {
  'DESCRIPTOR' : _SHORTLIST,
  '__module__' : 'inventory_pb2'
  # @@protoc_insertion_point(class_scope:ShortList)
  })
_sym_db.RegisterMessage(ShortList)


DESCRIPTOR._options = None

_INVENTORY = _descriptor.ServiceDescriptor(
  name='Inventory',
  full_name='Inventory',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=343,
  serialized_end=519,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStock',
    full_name='Inventory.GetStock',
    index=0,
    containing_service=None,
    input_type=_LEVELREQUEST,
    output_type=_STOCKITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ChangeStock',
    full_name='Inventory.ChangeStock',
    index=1,
    containing_service=None,
    input_type=_AMENDREQUEST,
    output_type=_AMENDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckShort',
    full_name='Inventory.CheckShort',
    index=2,
    containing_service=None,
    input_type=_SHORTREQUEST,
    output_type=_SHORTLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStore',
    full_name='Inventory.GetStore',
    index=3,
    containing_service=None,
    input_type=_SHORTREQUEST,
    output_type=_SHORTLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVENTORY)

DESCRIPTOR.services_by_name['Inventory'] = _INVENTORY

# @@protoc_insertion_point(module_scope)
