# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z*github.com/JBurton26/msoa-go/protos/order/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0border.proto\"3\n\x04Item\x12\n\n\x02ID\x18\x01 \x01(\t\x12\r\n\x05\x43ount\x18\x02 \x01(\x03\x12\x10\n\x08Location\x18\x03 \x01(\t\"\x82\x01\n\x0cOrderRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x10\n\x08Location\x18\x02 \x01(\t\x12\x0f\n\x07StaffID\x18\x03 \x01(\t\x12\x16\n\x07Trolley\x18\x04 \x01(\x0b\x32\x05.Cart\x12\x12\n\x05\x45mail\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05Total\x18\x06 \x01(\x01\x42\x08\n\x06_Email\"\x1d\n\rOrderResponse\x12\x0c\n\x04\x42ody\x18\x01 \x01(\t\"=\n\x04\x43\x61rt\x12\x14\n\x05Items\x18\x01 \x03(\x0b\x32\x05.Item\x12\r\n\x05Price\x18\x02 \x01(\x01\x12\x10\n\x08Location\x18\x03 \x01(\t\"9\n\tAddToCart\x12\x14\n\x05ToAdd\x18\x01 \x01(\x0b\x32\x05.Item\x12\x16\n\x07Trolley\x18\x02 \x01(\x0b\x32\x05.Cart2U\n\x05Order\x12 \n\x0b\x41\x64\x64ToBasket\x12\n.AddToCart\x1a\x05.Cart\x12*\n\tMakeOrder\x12\r.OrderRequest\x1a\x0e.OrderResponseB,Z*github.com/JBurton26/msoa-go/protos/order/b\x06proto3'
)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Item.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Count', full_name='Item.Count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='Item.Location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=66,
)


_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='OrderRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='OrderRequest.Location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StaffID', full_name='OrderRequest.StaffID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Trolley', full_name='OrderRequest.Trolley', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Email', full_name='OrderRequest.Email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Total', full_name='OrderRequest.Total', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_Email', full_name='OrderRequest._Email',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=69,
  serialized_end=199,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Body', full_name='OrderResponse.Body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=230,
)


_CART = _descriptor.Descriptor(
  name='Cart',
  full_name='Cart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Items', full_name='Cart.Items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Price', full_name='Cart.Price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='Cart.Location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=293,
)


_ADDTOCART = _descriptor.Descriptor(
  name='AddToCart',
  full_name='AddToCart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToAdd', full_name='AddToCart.ToAdd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Trolley', full_name='AddToCart.Trolley', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=352,
)

_ORDERREQUEST.fields_by_name['Trolley'].message_type = _CART
_ORDERREQUEST.oneofs_by_name['_Email'].fields.append(
  _ORDERREQUEST.fields_by_name['Email'])
_ORDERREQUEST.fields_by_name['Email'].containing_oneof = _ORDERREQUEST.oneofs_by_name['_Email']
_CART.fields_by_name['Items'].message_type = _ITEM
_ADDTOCART.fields_by_name['ToAdd'].message_type = _ITEM
_ADDTOCART.fields_by_name['Trolley'].message_type = _CART
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.message_types_by_name['Cart'] = _CART
DESCRIPTOR.message_types_by_name['AddToCart'] = _ADDTOCART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQUEST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderRequest)
  })
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORDERRESPONSE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderResponse)
  })
_sym_db.RegisterMessage(OrderResponse)

Cart = _reflection.GeneratedProtocolMessageType('Cart', (_message.Message,), {
  'DESCRIPTOR' : _CART,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:Cart)
  })
_sym_db.RegisterMessage(Cart)

AddToCart = _reflection.GeneratedProtocolMessageType('AddToCart', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOCART,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:AddToCart)
  })
_sym_db.RegisterMessage(AddToCart)


DESCRIPTOR._options = None

_ORDER = _descriptor.ServiceDescriptor(
  name='Order',
  full_name='Order',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=354,
  serialized_end=439,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddToBasket',
    full_name='Order.AddToBasket',
    index=0,
    containing_service=None,
    input_type=_ADDTOCART,
    output_type=_CART,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MakeOrder',
    full_name='Order.MakeOrder',
    index=1,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDER)

DESCRIPTOR.services_by_name['Order'] = _ORDER

# @@protoc_insertion_point(module_scope)
