# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z)github.com/JBurton26/msoa-go/protos/user/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nuser.proto\"\x1b\n\rIDUserRequest\x12\n\n\x02ID\x18\x01 \x01(\t\"!\n\rUNUserRequest\x12\x10\n\x08Username\x18\x01 \x01(\t\".\n\x0c\x41uthsRequest\x12\x10\n\x08Username\x18\x01 \x01(\t\x12\x0c\n\x04Pass\x18\x02 \x01(\t\"o\n\x0cUserResponse\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08Username\x18\x03 \x01(\t\x12!\n\x0b\x41\x63\x63\x65ssLevel\x18\x04 \x01(\x0e\x32\x0c.AccessLevel\x12\x10\n\x08Location\x18\x05 \x01(\t\"E\n\x0e\x41\x63\x63\x65ssResponse\x12!\n\x0b\x41\x63\x63\x65ssLevel\x18\x01 \x01(\x0e\x32\x0c.AccessLevel\x12\x10\n\x08Location\x18\x02 \x01(\t*G\n\x0b\x41\x63\x63\x65ssLevel\x12\x08\n\x04\x42\x41SE\x10\x00\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x01\x12\t\n\x05STAFF\x10\x02\x12\x0b\n\x07MANAGER\x10\x03\x12\t\n\x05\x41\x44MIN\x10\x04\x32\xb9\x01\n\x04User\x12,\n\x0bGetUserByID\x12\x0e.IDUserRequest\x1a\r.UserResponse\x12,\n\x0bGetUserByUN\x12\x0e.UNUserRequest\x1a\r.UserResponse\x12,\n\tGetAccess\x12\x0e.IDUserRequest\x1a\x0f.AccessResponse\x12\'\n\x05Login\x12\r.AuthsRequest\x1a\x0f.AccessResponseB+Z)github.com/JBurton26/msoa-go/protos/user/b\x06proto3'
)

_ACCESSLEVEL = _descriptor.EnumDescriptor(
  name='AccessLevel',
  full_name='AccessLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAFF', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANAGER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADMIN', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=310,
  serialized_end=381,
)
_sym_db.RegisterEnumDescriptor(_ACCESSLEVEL)

AccessLevel = enum_type_wrapper.EnumTypeWrapper(_ACCESSLEVEL)
BASE = 0
DEFAULT = 1
STAFF = 2
MANAGER = 3
ADMIN = 4



_IDUSERREQUEST = _descriptor.Descriptor(
  name='IDUserRequest',
  full_name='IDUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='IDUserRequest.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=41,
)


_UNUSERREQUEST = _descriptor.Descriptor(
  name='UNUserRequest',
  full_name='UNUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Username', full_name='UNUserRequest.Username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=76,
)


_AUTHSREQUEST = _descriptor.Descriptor(
  name='AuthsRequest',
  full_name='AuthsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Username', full_name='AuthsRequest.Username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Pass', full_name='AuthsRequest.Pass', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=124,
)


_USERRESPONSE = _descriptor.Descriptor(
  name='UserResponse',
  full_name='UserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='UserResponse.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='UserResponse.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Username', full_name='UserResponse.Username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AccessLevel', full_name='UserResponse.AccessLevel', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='UserResponse.Location', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=237,
)


_ACCESSRESPONSE = _descriptor.Descriptor(
  name='AccessResponse',
  full_name='AccessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccessLevel', full_name='AccessResponse.AccessLevel', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Location', full_name='AccessResponse.Location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=308,
)

_USERRESPONSE.fields_by_name['AccessLevel'].enum_type = _ACCESSLEVEL
_ACCESSRESPONSE.fields_by_name['AccessLevel'].enum_type = _ACCESSLEVEL
DESCRIPTOR.message_types_by_name['IDUserRequest'] = _IDUSERREQUEST
DESCRIPTOR.message_types_by_name['UNUserRequest'] = _UNUSERREQUEST
DESCRIPTOR.message_types_by_name['AuthsRequest'] = _AUTHSREQUEST
DESCRIPTOR.message_types_by_name['UserResponse'] = _USERRESPONSE
DESCRIPTOR.message_types_by_name['AccessResponse'] = _ACCESSRESPONSE
DESCRIPTOR.enum_types_by_name['AccessLevel'] = _ACCESSLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IDUserRequest = _reflection.GeneratedProtocolMessageType('IDUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:IDUserRequest)
  })
_sym_db.RegisterMessage(IDUserRequest)

UNUserRequest = _reflection.GeneratedProtocolMessageType('UNUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UNUserRequest)
  })
_sym_db.RegisterMessage(UNUserRequest)

AuthsRequest = _reflection.GeneratedProtocolMessageType('AuthsRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHSREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:AuthsRequest)
  })
_sym_db.RegisterMessage(AuthsRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

AccessResponse = _reflection.GeneratedProtocolMessageType('AccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:AccessResponse)
  })
_sym_db.RegisterMessage(AccessResponse)


DESCRIPTOR._options = None

_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=384,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserByID',
    full_name='User.GetUserByID',
    index=0,
    containing_service=None,
    input_type=_IDUSERREQUEST,
    output_type=_USERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserByUN',
    full_name='User.GetUserByUN',
    index=1,
    containing_service=None,
    input_type=_UNUSERREQUEST,
    output_type=_USERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccess',
    full_name='User.GetAccess',
    index=2,
    containing_service=None,
    input_type=_IDUSERREQUEST,
    output_type=_ACCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='User.Login',
    index=3,
    containing_service=None,
    input_type=_AUTHSREQUEST,
    output_type=_ACCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
